service: self-adaptive-memory-allocation
app: memory-intensive
org: tetzubko
frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  memorySize: 2048
  region: eu-central-1
  timeout: 500

functions:
  memory:
    runtime: python3.8
    handler: memory-intensive-handler.testFunction
    events:
      - http:
          method: get
          path: memory
  cpu:
    runtime: nodejs12.x
    handler: cpu-intensive-handler.timestamp
    events:
      - http:
          method: get
          path: cpu